// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AppResumed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static AppResumed GetRootAsAppResumed(ByteBuffer _bb) { return GetRootAsAppResumed(_bb, new AppResumed()); }
  public static AppResumed GetRootAsAppResumed(ByteBuffer _bb, AppResumed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AppResumed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)24; } }

  public static Offset<AppResumed> CreateAppResumed(FlatBufferBuilder builder,
      short opcode = 24) {
    builder.StartTable(1);
    AppResumed.AddOpcode(builder, opcode);
    return AppResumed.EndAppResumed(builder);
  }

  public static void StartAppResumed(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 24); }
  public static Offset<AppResumed> EndAppResumed(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<AppResumed>(o);
  }
};

