// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Chat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Chat GetRootAsChat(ByteBuffer _bb) { return GetRootAsChat(_bb, new Chat()); }
  public static Chat GetRootAsChat(ByteBuffer _bb, Chat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Chat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)14; } }
  public short ChatId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<Chat> CreateChat(FlatBufferBuilder builder,
      short opcode = 14,
      short chatId = 0) {
    builder.StartTable(2);
    Chat.AddChatId(builder, chatId);
    Chat.AddOpcode(builder, opcode);
    return Chat.EndChat(builder);
  }

  public static void StartChat(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 14); }
  public static void AddChatId(FlatBufferBuilder builder, short chatId) { builder.AddShort(1, chatId, 0); }
  public static Offset<Chat> EndChat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Chat>(o);
  }
};

