// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ForfeitMatch : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ForfeitMatch GetRootAsForfeitMatch(ByteBuffer _bb) { return GetRootAsForfeitMatch(_bb, new ForfeitMatch()); }
  public static ForfeitMatch GetRootAsForfeitMatch(ByteBuffer _bb, ForfeitMatch obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ForfeitMatch __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)3; } }

  public static Offset<ForfeitMatch> CreateForfeitMatch(FlatBufferBuilder builder,
      short opcode = 3) {
    builder.StartTable(1);
    ForfeitMatch.AddOpcode(builder, opcode);
    return ForfeitMatch.EndForfeitMatch(builder);
  }

  public static void StartForfeitMatch(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 3); }
  public static Offset<ForfeitMatch> EndForfeitMatch(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ForfeitMatch>(o);
  }
};

