// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MatchOver : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MatchOver GetRootAsMatchOver(ByteBuffer _bb) { return GetRootAsMatchOver(_bb, new MatchOver()); }
  public static MatchOver GetRootAsMatchOver(ByteBuffer _bb, MatchOver obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MatchOver __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Opcode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)11; } }
  public int PlayerScore { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int OpponentScore { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<MatchOver> CreateMatchOver(FlatBufferBuilder builder,
      short opcode = 11,
      int playerScore = 0,
      int opponentScore = 0) {
    builder.StartTable(3);
    MatchOver.AddOpponentScore(builder, opponentScore);
    MatchOver.AddPlayerScore(builder, playerScore);
    MatchOver.AddOpcode(builder, opcode);
    return MatchOver.EndMatchOver(builder);
  }

  public static void StartMatchOver(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddOpcode(FlatBufferBuilder builder, short opcode) { builder.AddShort(0, opcode, 11); }
  public static void AddPlayerScore(FlatBufferBuilder builder, int playerScore) { builder.AddInt(1, playerScore, 0); }
  public static void AddOpponentScore(FlatBufferBuilder builder, int opponentScore) { builder.AddInt(2, opponentScore, 0); }
  public static Offset<MatchOver> EndMatchOver(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MatchOver>(o);
  }
};

